### ISSUE TITLE
Azure Vnet Site: When co-ordinates are set, terraform is crashing

### ISSUE THREAD

**Issue by madhukar32** [volterraedge/terraform-provider-volterra#61]
panic: interface conversion: interface {} is float64, not float32
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0:
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: goroutine 275 [running]:
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: github.com/volterraedge/terraform-provider-volterra/volterra.resourceVolterraAzureVnetSiteCreate(0xc0003fd6c0, 0x7909440, 0xc001b5e358, 0x2, 0xcbca860)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	github.com/volterraedge/terraform-provider-volterra/volterra/resource_auto_volterra_azure_vnet_site.go:2266 +0x1b259
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc001879980, 0xc002487c20, 0xc00280d0a0, 0x7909440, 0xc001b5e358, 0x74e9001, 0xc0013fbcf8, 0xc00284a0c0)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/resource.go:305 +0x375
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0019e8a00, 0xc00280ba18, 0xc002487c20, 0xc00280d0a0, 0xc002818628, 0xc0021a32a8, 0x74ee420)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/schema/provider.go:294 +0x99
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0019f0000, 0xa0b7fe8, 0xc00248e7e0, 0xc0024920c0, 0xc0019f0000, 0xc00248e7e0, 0xc000289b80)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.8.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x79bdea0, 0xc0019f0000, 0xa0b7fe8, 0xc00248e7e0, 0xc002492060, 0x0, 0xa0b7fe8, 0xc00248e7e0, 0xc0019f7000, 0xac5)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.8.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc002630000, 0xa120998, 0xc0007b0300, 0xc002483b00, 0xc0006fe510, 0xcb46e80, 0x0, 0x0, 0x0)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	google.golang.org/grpc@v1.27.0/server.go:1024 +0x522
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: google.golang.org/grpc.(*Server).handleStream(0xc002630000, 0xa120998, 0xc0007b0300, 0xc002483b00, 0x0)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	google.golang.org/grpc@v1.27.0/server.go:1313 +0xd2c
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00063c6f0, 0xc002630000, 0xa120998, 0xc0007b0300, 0xc002483b00)
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	google.golang.org/grpc@v1.27.0/server.go:722 +0xab
2021-06-29T17:31:42.680-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-06-29T17:31:42.681-0700 [DEBUG] plugin.terraform-provider-volterra_v0.7.0: 	google.golang.org/grpc@v1.27.0/server.go:720 +0xa5
2021-06-29T17:31:42.688-0700 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/volterraedge/volterra/0.7.0/darwin_amd64/terraform-provider-volterra_v0.7.0 pid=12359 error="exit status 2"
2021/06/29 17:31:42 [DEBUG] volterra_azure_vnet_site.azure_site: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/06/29 17:31:42 [TRACE] EvalMaybeTainted: volterra_azure_vnet_site.azure_site encountered an error during creation, so it is now marked as tainted
2021/06/29 17:31:42 [TRACE] EvalWriteState: removing state object for volterra_azure_vnet_site.azure_site
2021/06/29 17:31:42 [TRACE] EvalApplyProvisioners: volterra_azure_vnet_site.azure_site has no state, so skipping provisioners
2021/06/29 17:31:42 [TRACE] EvalMaybeTainted: volterra_azure_vnet_site.azure_site encountered an error during creation, so it is now marked as tainted
2021/06/29 17:31:42 [TRACE] EvalWriteState: removing state object for volterra_azure_vnet_site.azure_site
2021/06/29 17:31:42 [TRACE] vertex "volterra_azure_vnet_site.azure_site": visit complete
2021/06/29 17:31:42 [TRACE] dag/walk: upstream of "volterra_tf_params_action.action_test" errored, so skipping
2021/06/29 17:31:42 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/volterraedge/volterra\"] (close)" errored, so skipping
2021/06/29 17:31:42 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/06/29 17:31:42 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/06/29 17:31:42 [TRACE] statemgr.Filesystem: no original state snapshot to back up
2021/06/29 17:31:42 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 3
2021/06/29 17:31:42 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/06/29 17:31:42 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/06/29 17:31:42 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-06-29T17:31:42.718-0700 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by memes** [comment]
FYI this happens on GCP and AWS too - was about to open an issue myself.

**Comment by JeffGiroux** [comment]
Any updates on this? I just created an azure vnet site and it put my gps coordinates SW of Africa continent. I would prefer to have GPS in there.

**Comment by madhukar32** [comment]
@memes @JeffGiroux: Will fix this issue during the August 26th release. The workaround is not to set the co-ordinates through the site object, by default using the region the backend picks the right co-ordinates. This field is only used when you want to override the default co-ordinates.

**Comment by JeffGiroux** [comment]
Hmm, "backend picks the right co-ordinates".

When I stood up a sight in us-west-2 US the other day, the Geo map in VoltConsole for my Azure VNet site was just off the coast of Africa. Is something not updating correctly in order for gps to be accurate?

**Comment by madhukar32** [comment]
@JeffGiroux: Can you send me the details of your site and tenant? Between did u enter `us-west-2` as your region or `westus2`?

**Comment by JeffGiroux** [comment]
Hmm, for azure...sorry. Meant westus2. Here's my repo and variables. The volterra site creation is in the volterrasites.tf file.

https://github.com/f5devcentral/f5-digital-customer-engagement-center/tree/azure-volterra-sites/solutions/security/multi-cloud-connectivity-volterra/azure

**Comment by JeffGiroux** [comment]
What is status of this bug? Was this fix released in last update? If not, then when is expected delivery of fix? Thx,

**Comment by madhukar32** [comment]
@JeffGiroux: This bug is fixed in last release. Can you pls test?

**Comment by JeffGiroux** [comment]
Did this address only Azure or does it address all currently supported cloud sites: AWS, Google, Azure? Curious before I start my test up again.

**Comment by madhukar32** [comment]
It should be fixed for all cloud sites

**Comment by JeffGiroux** [comment]
I tested on azure and google and both work great.
